"""add enum value to default

Revision ID: 0308a629a3f3
Revises: 69c30dfe081f
Create Date: 2026-05-19 10:07:01.360838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0308a629a3f3'
down_revision: Union[str, None] = '69c30dfe081f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
