"""add participation_mode to interviews

Revision ID: 1125bf9c6307
Revises: 182e01c9ede0
Create Date: 2026-05-19 07:22:40.249473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1125bf9c6307'
down_revision: Union[str, None] = '182e01c9ede0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('participation_mode', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'participation_mode')
    # ### end Alembic commands ###
