"""made timestamp columns timezone-aware


Revision ID: 182e01c9ede0
Revises: d30baf686b6f
Create Date: 2026-05-18 14:51:22.566235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '182e01c9ede0'
down_revision: Union[str, None] = 'd30baf686b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_summaries', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_start AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_end AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_participants', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="joined_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_summaries', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspace_invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspace_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="joined_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_members', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="joined_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_invites', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_summaries', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_participants', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="joined_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_end AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_start AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_summaries', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # ### end Alembic commands ###
