"""add started_at to interviews

Revision ID: 26db59e0e822
Revises: 4ebdeb2c43d6
Create Date: 2026-05-29 15:54:39.980396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26db59e0e822'
down_revision: Union[str, None] = '4ebdeb2c43d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('interviews', 'started_at')
    # ### end Alembic commands ###
