"""add_data_deletion_audit_logs_table

Revision ID: 40d4bb99e63d
Revises: 4ebdeb2c43d6
Create Date: 2026-06-05 09:03:55.316695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40d4bb99e63d'
down_revision: Union[str, None] = '4ebdeb2c43d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_deletion_audit_logs',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=True),
    sa.Column('deletion_type', sa.String(length=50), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deletion_audit_session_id', 'data_deletion_audit_logs', ['session_id'], unique=False)
    op.create_index('ix_deletion_audit_status', 'data_deletion_audit_logs', ['status'], unique=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_deletion_audit_status', table_name='data_deletion_audit_logs')
    op.drop_index('ix_deletion_audit_session_id', table_name='data_deletion_audit_logs')
    op.drop_table('data_deletion_audit_logs')
    # ### end Alembic commands ###
