"""added columns to match new onboarding support

Revision ID: 4220c2a1fc6a
Revises: 4484271ac63a
Create Date: 2026-05-20 13:31:45.075812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4220c2a1fc6a'
down_revision: Union[str, None] = '4484271ac63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interview_preferences', sa.Column('tone', sa.String(length=80), nullable=True))
    op.add_column('user_meeting_preferences', sa.Column('auto_record', sa.Boolean(), nullable=True))
    op.add_column('user_meeting_preferences', sa.Column('announce', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('hires', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hires')
    op.drop_column('user_meeting_preferences', 'announce')
    op.drop_column('user_meeting_preferences', 'auto_record')
    op.drop_column('user_interview_preferences', 'tone')
    # ### end Alembic commands ###
