"""add strengths and weaknesses to scorecard_sub_rubrics

Revision ID: 5c291baa8023
Revises: 7a50f276157c
Create Date: 2026-06-05 20:35:17.353248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c291baa8023'
down_revision: Union[str, None] = '7a50f276157c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scorecard_sub_rubrics', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('scorecard_sub_rubrics', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('scorecard_sub_rubrics', 'weaknesses')
    op.drop_column('scorecard_sub_rubrics', 'strengths')
    # ### end Alembic commands ###
