"""add scorecard sub-rubrics, evidence, confidence, justification, strengths, weaknesses

Revision ID: 6dfc72e0da4a
Revises: 40d4bb99e63d
Create Date: 2026-06-05 21:56:13.335703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6dfc72e0da4a'
down_revision: Union[str, None] = '40d4bb99e63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecard_sub_rubrics',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('score_pct', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scorecard_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecard_evidence',
    sa.Column('score_id', sa.UUID(), nullable=True),
    sa.Column('sub_rubric_id', sa.UUID(), nullable=True),
    sa.Column('question_turn_id', sa.Text(), nullable=False),
    sa.Column('response_turn_id', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scorecard_scores.id'], ),
    sa.ForeignKeyConstraint(['sub_rubric_id'], ['scorecard_sub_rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scorecard_scores', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('scorecard_scores', sa.Column('justification', sa.Text(), nullable=True))
    op.alter_column('scorecard_signals', 'label',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scorecard_signals', 'label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('scorecard_scores', 'justification')
    op.drop_column('scorecard_scores', 'confidence')
    op.drop_table('scorecard_evidence')
    op.drop_table('scorecard_sub_rubrics')
    # ### end Alembic commands ###
