"""add rescheduled_at to interviews

Revision ID: 7061d9a99af7
Revises: c942e249852d
Create Date: 2026-05-28 19:51:12.306381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7061d9a99af7'
down_revision: Union[str, None] = 'c942e249852d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('rescheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'rescheduled_at')
    # ### end Alembic commands ###
