"""add_scorecard_sub_rubrics_and_evidence_tables

Revision ID: 7a50f276157c
Revises: e23b6b2fe2d6
Create Date: 2026-06-05 18:41:09.291311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a50f276157c'
down_revision: Union[str, None] = 'e23b6b2fe2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecard_sub_rubrics',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('score_pct', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scorecard_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecard_evidence',
    sa.Column('score_id', sa.UUID(), nullable=True),
    sa.Column('sub_rubric_id', sa.UUID(), nullable=True),
    sa.Column('question_turn_id', sa.Text(), nullable=False),
    sa.Column('response_turn_id', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scorecard_scores.id'], ),
    sa.ForeignKeyConstraint(['sub_rubric_id'], ['scorecard_sub_rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorecard_evidence')
    op.drop_table('scorecard_sub_rubrics')
    # ### end Alembic commands ###
