"""update timestamp_ms to use BigInt

Revision ID: 7cf6a2a862fa
Revises: 1125bf9c6307
Create Date: 2026-05-25 15:44:06.430330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7cf6a2a862fa'
down_revision: Union[str, None] = '1125bf9c6307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdk_sessions')
    op.drop_index(op.f('ix_sdk_zoom_oauth_tokens_zoom_user_id'), table_name='sdk_zoom_oauth_tokens')
    op.drop_table('sdk_zoom_oauth_tokens')
    op.drop_index(op.f('ix_sdk_provider_events_session_id'), table_name='sdk_provider_events')
    op.drop_table('sdk_provider_events')
    op.drop_index(op.f('ix_sdk_transcript_turns_session_id'), table_name='sdk_transcript_turns')
    op.drop_table('sdk_transcript_turns')
    op.alter_column('interviews', 'participation_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'standard'::character varying"))
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('interviews', 'participation_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'standard'::character varying"))
    op.create_table('sdk_transcript_turns',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('speaker_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('speaker_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_stream_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sequence_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trigger_reason', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sdk_transcript_turns_pkey')),
    sa.UniqueConstraint('session_id', 'sequence_no', name=op.f('sdk_transcript_turns_session_id_sequence_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sdk_transcript_turns_session_id'), 'sdk_transcript_turns', ['session_id'], unique=False)
    op.create_table('sdk_provider_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_stream_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payload_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sdk_provider_events_pkey')),
    sa.UniqueConstraint('provider', 'event_id', name=op.f('sdk_provider_events_provider_event_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sdk_provider_events_session_id'), 'sdk_provider_events', ['session_id'], unique=False)
    op.create_table('sdk_zoom_oauth_tokens',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zoom_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('access_token_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sdk_zoom_oauth_tokens_pkey'))
    )
    op.create_index(op.f('ix_sdk_zoom_oauth_tokens_zoom_user_id'), 'sdk_zoom_oauth_tokens', ['zoom_user_id'], unique=False)
    op.create_table('sdk_sessions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meeting_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wake_words_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('provider_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sdk_sessions_pkey'))
    )
    # ### end Alembic commands ###
