"""add meeting fields participation and cv

Revision ID: 7fdd5e7621c4
Revises: d30baf686b6f
Create Date: 2026-05-18 01:57:44.931471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7fdd5e7621c4'
down_revision: Union[str, None] = 'd30baf686b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_summaries', sa.Column('cv_text', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('meeting_link', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('participation_mode', sa.Enum('PASSIVE', 'STANDARD', 'PROACTIVE', name='participationmode'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'participation_mode')
    op.drop_column('interviews', 'meeting_link')
    op.drop_column('interview_summaries', 'cv_text')
    # ### end Alembic commands ###
