"""added columns for candidates and interviews

Revision ID: a1df2ff87e17
Revises: c942e249852d
Create Date: 2026-05-29 02:48:50.655249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1df2ff87e17'
down_revision: Union[str, None] = 'c942e249852d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('current_role', sa.String(length=120), nullable=True))
    op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('interviews', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'interviews', 'interview_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'started_at')
    op.drop_column('interviews', 'session_id')
    op.drop_column('candidates', 'skills')
    op.drop_column('candidates', 'years_of_experience')
    op.drop_column('candidates', 'current_role')
    # ### end Alembic commands ###
