"""change scorecard_signals label to Text

Revision ID: b32f66cb0043
Revises: 4ebdeb2c43d6
Create Date: 2026-06-05 11:35:27.473889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b32f66cb0043'
down_revision: Union[str, None] = '4ebdeb2c43d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scorecard_signals', 'label',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scorecard_signals', 'label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
