"""added_new_fields_to_candidate_and_session_id

Revision ID: c942e249852d
Revises: eefbaee7d688
Create Date: 2026-05-26 19:06:51.130024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c942e249852d'
down_revision: Union[str, None] = 'eefbaee7d688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('candidates', sa.Column('current_role', sa.String(length=120), nullable=True))
    op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'location')
    op.drop_column('candidates', 'current_role')
    op.drop_column('candidates', 'years_of_experience')
    op.drop_column('candidates', 'skills')
    # ### end Alembic commands ###

