"""updated datetime columns to be timezone aware

Revision ID: d2cb77d188c2
Revises: ff170e45b0ab
Create Date: 2026-05-18 03:22:19.771816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd2cb77d188c2'
down_revision: Union[str, None] = 'ff170e45b0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_summaries', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_start AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_end AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_participants', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="joined_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_summaries', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspace_invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_invites', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_summaries', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_participants', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="joined_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_end AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'scheduled_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_start AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_summaries', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # ### end Alembic commands ###
