"""add onboarding and user trial

Revision ID: d30baf686b6f
Revises: 62e9bff51378
Create Date: 2026-05-15 16:54:41.618598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd30baf686b6f'
down_revision: Union[str, None] = '62e9bff51378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('language', sa.String(length=20), nullable=True))
    # Safe two-step for onboarding_completed
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.execute("UPDATE users SET onboarding_completed = FALSE WHERE onboarding_completed IS NULL")
    op.alter_column('users', 'onboarding_completed', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'language')
    op.drop_table('user_trials')
    # ### end Alembic commands ###
