"""add notifications table

Revision ID: e797dcd4433c
Revises: c942e249852d
Create Date: 2026-05-28 19:12:32.855810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e797dcd4433c'
down_revision: Union[str, None] = 'c942e249852d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('candidates', sa.Column('current_role', sa.String(length=120), nullable=True))
    # op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    # op.add_column('candidates', sa.Column('skills', sa.Text(), nullable=True))
    # op.add_column('interviews', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'interviews', 'interview_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'session_id')
    op.drop_column('candidates', 'skills')
    op.drop_column('candidates', 'years_of_experience')
    op.drop_column('candidates', 'current_role')
    op.drop_table('notifications')
    # ### end Alembic commands ###
