"""Add interview sessions table

Revision ID: eefbaee7d688
Revises: 1125bf9c6307
Create Date: 2026-05-24 09:56:11.350754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eefbaee7d688'
down_revision: Union[str, None] = '1125bf9c6307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('questions_json', sa.Text(), nullable=False),
    sa.Column('rubric_json', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('closing', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transcript_json', sa.Text(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('interviews', 'participation_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'standard'::character varying"))
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('interviews', 'participation_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'standard'::character varying"))
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
