"""add_meeting_fields_participation_and_cv

Revision ID: ff170e45b0ab
Revises: d30baf686b6f
Create Date: 2026-05-18 02:50:23.570695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff170e45b0ab'
down_revision: Union[str, None] = 'd30baf686b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_summaries', sa.Column('cv_text', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('meeting_link', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('participation_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'participation_mode')
    op.drop_column('interviews', 'meeting_link')
    op.drop_column('interview_summaries', 'cv_text')
    # ### end Alembic commands ###
